app/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the Closure to execute when that URI is requested.
|
*/

Route::filter('auth', function()
{
    if ( Auth::guest() ) // If the user is not logged in
    {
        return Redirect::guest('user/login');
    }
});

// Only authenticated users will be able to access routes that begins with
// 'admin'. Ex: 'admin/posts', 'admin/categories'.
Route::when('admin*', 'auth'); 

Route::get('/', 'HomeController@showWelcome');

Route::get('admin', array('as' => 'admin..dashboard.index', 'uses' => 'admin\DashboardController@index'));

Route::resource('/pages', 'PagesController');

Route::get('/posts/tags/{tags}', array('as' => 'post.index.tag', 'uses' => 'PostsController@index_tag'));
Route::get('/posts/category/{id}', array('as' => 'post.index.category', 'uses' => 'PostsController@index_category'));
Route::resource('/posts', 'PostsController');

Route::get('/products/tags/{tags}', array('as' => 'products.index.tag', 'uses' => 'ProductsController@index_tag'));
Route::get('/products/category/{id}', array('as' => 'products.index.category', 'uses' => 'ProductsController@index_category'));
Route::resource('/products', 'ProductsController');

Route::resource('/portfolios', 'PortfoliosController');
Route::get('/portfolios/{id}/box', array('uses' => 'PortfoliosController@show_box'));

Route::post('/upload', array('as' => 'upload', 'uses' => 'UploadController@upload'));

Route::group(array('prefix' => 'admin'), function() {
	Route::resource('/posts', 'admin\PostsController');
	Route::get( '/posts/{id}/translation', array('as' => 'admin..post_translations.set', 'uses' => 'admin\PostTranslationsController@set_translation'));
	Route::post('/posts/{id}/translation', array('as' => 'admin..post_translations.store', 'uses' => 'admin\PostTranslationsController@store'));
	Route::resource('/portfolios', 'admin\PortfoliosController');
	Route::get( '/portfolios/{id}/translation', array('as' => 'admin..portfolio_translations.set', 'uses' => 'admin\PortfolioTranslationsController@set_translation'));
	Route::post('/portfolios/{id}/translation', array('as' => 'admin..portfolio_translations.store', 'uses' => 'admin\PortfolioTranslationsController@store'));
	Route::resource('/pages', 'admin\PagesController');
	Route::get( '/pages/{id}/translation', array('as' => 'admin..page_translations.set', 'uses' => 'admin\PageTranslationsController@set_translation'));
	Route::post('/pages/{id}/translation', array('as' => 'admin..page_translations.store', 'uses' => 'admin\PageTranslationsController@store'));
	Route::resource('/settings', 'admin\SettingsController');
	Route::resource('/categories', 'admin\CategoriesController');
	Route::resource('/products', 'admin\ProductsController');
	Route::resource('/product_categories', 'admin\ProductCategoriesController');
	Route::get( '/products/{id}/translation', array('as' => 'admin..product_translations.set', 'uses' => 'admin\ProductTranslationsController@set_translation'));
	Route::post('/products/{id}/translation', array('as' => 'admin..product_translations.store', 'uses' => 'admin\ProductTranslationsController@store'));
	Route::resource('/users', 'admin\UsersController');
	Route::resource('/menus', 'admin\MenusController');
	Route::post('/menus_update', array('uses' => 'admin\MenusController@updateList'));
	Route::get('sitemap', array('as' => 'admin..sitemap.index', 'uses' => 'admin\SitemapController@index'));
});
Route::get('sitemap.xml', function(){ return Redirect::to('sitemap_index.xml'); });
Route::get('sitemap_index.xml', function(){ return View::make('sitemap_index'); });
Route::get('post-sitemap.xml', array('as' => 'admin..sitemap.index', 'uses' => 'admin\SitemapController@index'));
// Confide routes
Route::get( 'login',                  	   'UserController@login');
Route::get( 'user/login',                  'UserController@login');
Route::post('user/login',                  array( 'as'=>'user..login.do_login', 'uses' => 'UserController@do_login'));
Route::get( 'user/confirm/{code}',         'UserController@confirm');
Route::get( 'user/forgot_password',        'UserController@forgot_password');
Route::post('user/forgot_password',        'UserController@do_forgot_password');
Route::get( 'user/reset_password/{token}', 'UserController@reset_password');
Route::post('user/reset_password',         'UserController@do_reset_password');
Route::get( 'user/logout',                 'UserController@logout');

Route::post('contact', function() {

    $fromEmail = Input::get('email');
    $fromName = Input::get('email');
    $subject = Input::get('subject');
    $data = array( 'message' => Input::get('message') );

    $toEmail = 'waycs16@gmail.com';
    $toName = 'Advance Enpower';

    Mail::send('emails.contact', $data, function($message) use ($toEmail, $toName, $fromEmail, $fromName, $subject)
    {
        $message->to($toEmail, $toName);

        $message->from($fromEmail, $fromName);

        $message->subject($subject);
    });
    
    return Redirect::back();
});

app/models/Category.php
<?php

class Category extends Eloquent {
    public $timestamps = false;

	protected $guarded = array();
  
	protected $attributes = array(
		'name_en' => '',
		'name_th' => '',
		'category_id' => '0'
	);


	public static $rules = array(
		'name' => 'required'
	);

	public function posts(){
		return $this->belongsToMany('Post', 'categories_posts', 'category_id', 'post_id');
	}

	public function parent(){
		return $this->belongsTo('Category', 'category_id');
	}

	public function subCategories(){
		return $this->hasMany('Category', 'category_id');
	}
}

app/controllers/admin/CategoriesController.php
<?php
namespace admin;

use Illuminate\Support\Facades\View;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Validator;
use Illuminate\Support\Facades\Redirect;
use Category;
use DB;
use User;

class CategoriesController extends \BaseController {

	/**
	 * Category Repository
	 *
	 * @var Category
	 */
	protected $category;

	public function __construct(Category $category)
	{
		$this->category = $category;
	}

	/**
	 * Display a listing of the resource.
	 *
	 * @return Response
	 */
	public function index()
	{
		$categories = Category::with('subCategories')->where('category_id', '0')->get();

		return View::make('admin.categories.index', compact('categories'));
	}

	/**
	 * Show the form for creating a new resource.
	 *
	 * @return Response
	 */
	public function create()
	{
		$categories = Category::with('subCategories')->where('category_id', '0')->get();

		return View::make('admin.categories.index', compact('categories'));
	}

	/**
	 * Store a newly created resource in storage.
	 *
	 * @return Response
	 */
	public function store()
	{
		$input = Input::all();
		
		$input['name'] = $input['name_th'].' - '.$input['name_en'];

		$validation = Validator::make($input, Category::$rules);

		if ($validation->passes())
		{
			$category = $this->category->create($input);

			return Redirect::route('admin..categories.index');
		}

		return Redirect::route('admin..categories.index')
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Show the form for editing the specified resource.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function edit($id)
	{
		$category = $this->category->find($id);
		$categories = Category::with('subCategories')->where('category_id', '0')->get();

		if (is_null($category))
		{
			return Redirect::route('admin.categories.index');
		}

		return View::make('admin.categories.index', compact('category', 'categories'));
	}

	/**
	 * Update the specified resource in storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function update($id)
	{
		$input = array_except(Input::all(), '_method');

		$input['name'] = $input['name_th'].' - '.$input['name_en'];

		$validation = Validator::make($input, Category::$rules);

		if ($validation->passes())
		{
			$category = $this->category->find($id);
			$category->update($input);
			
			return Redirect::route('admin..categories.index', $id);
		}

		return Redirect::route('admin..categories.index', $id)
			->withInput()
			->withErrors($validation)
			->with('message', 'There were validation errors.');
	}

	/**
	 * Remove the specified resource from storage.
	 *
	 * @param  int  $id
	 * @return Response
	 */
	public function destroy($id)
	{
		$this->category->find($id)->delete();

		return Redirect::route('admin..categories.index');
	}

}

app/views/admin/categories/index.blade.php
@extends('admin.layouts.admin')

@section('main')

<div class="row">
	<div class="col-lg-12">
		<h1>All Post Category</h1>

        @if ($errors->any())
        	<div class="alert alert-danger">
        	    <ul>
                    {{ implode('', $errors->all('<li class="error">:message</li>')) }}
                </ul>
        	</div>
        @endif
    </div>
    <div class=" col-lg-4">
    <?php $parent_categories = Category::lists('name', 'id'); 
    	$parent_categories = array('0' => 'No parent category') + $parent_categories;
    	$category_id = Input::old('category_id') ? Input::old('category_id') : Input::get('category_id');
    	$submittext = isset($category) ? 'Edit' : 'Add new post category';
    ?>
    @if(!isset($category))
    	{{ Form::open(array('route' => 'admin..categories.store', 'class' => 'form-horizontal')) }}
	@else
		{{ Form::model($category, array('class' => 'form-horizontal', 'method' => 'PATCH', 'route' => array('admin..categories.update', $category->id))) }}
	@endif
		    <div class="panel panel-default">
		    	<div class="panel-heading">
		            Add new post category
		        </div>
		    	<div class="panel-body">
		    		<div class="form-group">
			            
			            <div class="col-sm-12">{{ Form::label('name_th', 'Name Default:', array('class'=>'control-label')) }}
			              {{ Form::text('name_th', Input::old('name_th'), array('class'=>'form-control', 'placeholder'=>'Name Default')) }}
			            </div>
			        </div>

		    		<div class="form-group">
			            <div class="col-sm-12">
			            {{ Form::label('name_en', 'Name English:', array('class'=>'control-label')) }}
			              {{ Form::text('name_en', Input::old('name_en'), array('class'=>'form-control', 'placeholder'=>'Name English')) }}
			            </div>
			        </div>

			        <div class="form-group">
			            <div class="col-sm-12">
			            {{ Form::label('slug', 'Friendly Url:', array('class'=>'control-label')) }}
			              {{ Form::text('slug', Input::old('slug'), array('class'=>'form-control', 'placeholder'=>'Friendly Url')) }}
			            </div>
			        </div>

		    		<div class="form-group">
			            <div class="col-sm-12">
			            {{ Form::label('category_id', 'Parent category:', array('class'=>'control-label')) }}
			              {{ Form::select('category_id', $parent_categories, $category_id, array('class'=>'form-control', 'placeholder'=>'ประเภทหลัก')) }}
			            </div>
			        </div>
				</div>
				<div class="panel-footer">
       				 {{ Form::submit($submittext, array('class' => 'btn  btn-primary', 'data-disable-with'=>"Saving...")) }}
	            </div>
		    </div>
		{{ Form::close() }}
    </div>

    <div class="panel col-lg-8">	
    	
		<div  class="tree well">
			<ul>
				<li><span><i class="fa fa-home fa-fw"></i>Root</span>
				<ul id="sortable">
		@if ($categories->count())
					@foreach ($categories as $category)
						
					<li>
						<span><i class="fa fa-tablet fa-fw"></i>{{{ $category->name }}}</span>
						<span>{{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin..categories.destroy', $category->id))) }}
		                        {{ Form::submit('Delete', array('class' => 'btn btn-danger btn-xs', 'data-confirm' => 'Are you sure?')) }}
		                    {{ Form::close() }}
		                    {{ link_to_route('admin..categories.edit', 'Edit', array($category->id), array('class' => 'btn btn-info btn-xs')) }}
		          		</span>
		          		<span>{{ link_to_route('admin..categories.create', 'Add sub category', array('category_id' => $category->id), array('class' => 'btn btn-primary btn-xs')) }}</span>
					
		          		<?php $subcategories = Category::where('category_id', $category->id)->get(); ?>
		          		@if($subcategories->count() > 0 )
		          			<ul id="sortable">
		          			@foreach ($subcategories as $subcategory)
		          				<li>
		          				<span><i class="fa fa-tablet fa-fw"></i>{{{ $subcategory->name }}}</span>
												<span>{{ Form::open(array('style' => 'display: inline-block;', 'method' => 'DELETE', 'route' => array('admin..categories.destroy', $subcategory->id))) }}
				                        {{ Form::submit('Delete', array('class' => 'btn btn-danger btn-xs', 'data-confirm' => 'Are you sure?')) }}
				                    {{ Form::close() }}
				                    {{ link_to_route('admin..categories.edit', 'Edit', array($subcategory->id), array('class' => 'btn btn-info btn-xs')) }}
				          		</span>
		          				</li>
							@endforeach		
		          			</ul>
		          		@endif
					</li>
					@endforeach	
		@else
					<li>
						<span>No category</span>
					</li>
		@endif	
				</ul>
				</li>
			</ul>
		</div>
    </div>
</div>
@stop